dbt_third:
  target: dev
  outputs:
    dev:
      type: mysql
      server: localhost
      port: 3306
      database: my_dbt_db
      schema: my_dbt_db
      username: root
      password: Romochka
      driver: MySQL ODBC 8.0 ANSI Driver